# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160409_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='top_background_image_width',
            new_name='top_background_image_height',
        ),
    ]
