# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('header', '0004_auto_20160408_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='brand_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='menu',
            name='brand_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
