# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_auto_20160408_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='brand_image_height',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='brand_image_width',
            field=models.IntegerField(default=20),
        ),
    ]
