# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_auto_20160408_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='brand_image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='brand_image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
