# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloglandingpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogLandingPage',
            new_name='BlogListView',
        ),
    ]
