# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160320_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistview',
            name='intro',
            field=models.CharField(max_length=255),
        ),
    ]
